# Generated by Django 5.1.3 on 2024-11-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.PositiveIntegerField()),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_first_name', models.CharField(max_length=100)),
                ('borrower_last_name', models.CharField(max_length=100)),
                ('borrower_middle_name', models.CharField(blank=True, max_length=100)),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='borrowed', max_length=10)),
                ('datenow', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
